(* Wolfram Language package *)

BeginPackage["StripeCurrencies`"];

$StripeCodeToCurrency::usage = "";
$StripeCurrencyToCode::usage = "";
$StripeCurrencies::usage = "";
$StripeNoCent::usage = "";
$StripeInterpreterCountryList::usage = "";

Begin["`Private`"];

$StripeCurrencyToCode = {"UAEDirhams" -> "aed", "AfghanAfghani" -> "afn", 
 "AlbanianLeke" -> "all", "ArmenianDram" -> "amd", 
 "NetherlandsAntillesGuilders" -> "ang", "AngolanKwanza" -> "aoa", 
 "ArgentinePesos" -> "ars", "AustralianDollars" -> "aud", 
 "ArubanFlorins" -> "awg", "AzerbaijaniManat" -> "azn", 
 "BosnianHerzegovinianMaraka" -> "bam", "BarbadianDollars" -> "bbd", 
 "BangladeshiTaka" -> "bdt", "BulgarianLeva" -> "bgn", 
 "BurundiFrancs" -> "bif", "BermudaDollars" -> "bmd", 
 "BruneiDollars" -> "bnd", "BolivianBolivianos" -> "bob", 
 "BrazilianReais" -> "brl", "BahamianDollars" -> "bsd", 
 "BotswanaPula" -> "bwp", "BelizeDollars" -> "bzd", 
 "CanadianDollars" -> "cad", "CongoleseFranc" -> "cdf", 
 "SwissFrancs" -> "chf", "ChileanPesos" -> "clp", 
 "ChineseYuan" -> "cny", "ColombianPesos" -> "cop", 
 "CostaRicanColones" -> "crc", "CapeVerdeanEscudos" -> "cve", 
 "CzechKoruny" -> "czk", "DjiboutiFrancs" -> "djf", 
 "DanishKroner" -> "dkk", "DominicanPesos" -> "dop", 
 "AlgerianDinars" -> "dzd", "EgyptianPounds" -> "egp", 
 "EthiopianBirr" -> "etb", "Euros" -> "eur", "FijianDollars" -> "fjd",
 "FalklandIslandsPounds" -> "fkp", "BritishPounds" -> "gbp", 
 "GeorgianLari" -> "gel", "GibraltarPounds" -> "gip", 
 "GambianDalasi" -> "gmd", "GuineaFrancs" -> "gnf", 
 "GuatemalaQuetzales" -> "gtq", "GuyaneseDollars" -> "gyd", 
 "HongKongDollars" -> "hkd", "HonduranLempiras" -> "hnl", 
 "CroatianKuna" -> "hrk", "HaitiGourdes" -> "htg", 
 "HungarianForints" -> "huf", "IndonesianRupiahs" -> "idr", 
 "IsraeliShekels" -> "ils", "IndianRupees" -> "inr", 
 "IcelandKronur" -> "isk", "JamaicanDollars" -> "jmd", "Yen" -> "jpy",
 "KenyanShillings" -> "kes", "KyrgyzstanSom" -> "kgs", 
 "CambodianRiels" -> "khr", "ComorosFrancs" -> "kmf", 
 "KoreanWon" -> "krw", "CaymanIslandsDollars" -> "kyd", 
 "KazakhstanTenge" -> "kzt", "LaoKips" -> "lak", 
 "LebanesePounds" -> "lbp", "SriLankaRupees" -> "lkr", 
 "LiberianDollars" -> "lrd", "LesothoMaloti" -> "lsl", 
 "MoroccanDirhams" -> "mad", "MoldovanLei" -> "mdl", 
 "MalagasyAriary" -> "mga", "MacedonianDenars" -> "mkd", 
 "MongolianTugrik" -> "mnt", "MacauPatacas" -> "mop", 
 "MauritanianOuguiya" -> "mro", "MauritiusRupees" -> "mur", 
 "MaldivesRufiyaa" -> "mvr", "MalawiKwacha" -> "mwk", 
 "MexicanPesos" -> "mxn", "MalaysianRinggits" -> "myr", 
 "MozambiqueMeticais" -> "mzn", "NamibianDollars" -> "nad", 
 "NigerianNaira" -> "ngn", "NicaraguaCordobas" -> "nio", 
 "NorwegianKroner" -> "nok", "NepaleseRupees" -> "npr", 
 "NewZealandDollars" -> "nzd", "PanamaBalboas" -> "pab", 
 "PeruvianSoles" -> "pen", "PapuaNewGuineaKina" -> "pgk", 
 "PhilippinePesos" -> "php", "PakistaniRupees" -> "pkr", 
 "PolishZlotych" -> "pln", "ParaguayanGuaranies" -> "pyg", 
 "QatarRials" -> "qar", "RomanianLei" -> "ron", 
 "SerbianDinars" -> "rsd", "RussianRubles" -> "rub", 
 "RwandaFrancs" -> "rwf", "SaudiArabianRiyals" -> "sar", 
 "SolomonIslandsDollars" -> "sbd", "SeychellesRupees" -> "scr", 
 "SwedishKronor" -> "sek", "SingaporeDollars" -> "sgd", 
 "SaintHelenaPounds" -> "shp", "SierraLeoneLeones" -> "sll", 
 "SomaliShillings" -> "sos", "SurinameDollars" -> "srd", 
 "SaoTomeDobras" -> "std", "ElSalvadorColones" -> "svc", 
 "SwazilandEmalangeni" -> "szl", "ThaiBaht" -> "thb", 
 "TajikistanSomoni" -> "tjs", "TongaPaanga" -> "top", 
 "TurkishLiras" -> "try", "TrinidadTobagoDollars" -> "ttd", 
 "TaiwanDollars" -> "twd", "TanzanianShillings" -> "tzs", 
 "UkraineHryven" -> "uah", "UgandanShillings" -> "ugx", 
 "USDollars" -> "usd", "UruguayanPesos" -> "uyu", 
 "UzbekistanSom" -> "uzs", "VietnameseDong" -> "vnd", 
 "VanuatuVatu" -> "vuv", "SamoanTala" -> "wst", 
 "CentralAfricanCFAFrancs" -> "xaf", "EastCaribbeanDollars" -> "xcd", 
 "WestAfricanCFAFrancs" -> "xof", "PacificFrancs" -> "xpf", 
 "YemenRiyals" -> "yer", "SouthAfricanRand" -> "zar", 
 "ZambianKwacha" -> "zmw"}
 
$StripeCodeToCurrency = {"aed" -> "UAEDirhams", "afn" -> "AfghanAfghani", 
 "all" -> "AlbanianLeke", "amd" -> "ArmenianDram", 
 "ang" -> "NetherlandsAntillesGuilders", "aoa" -> "AngolanKwanza", 
 "ars" -> "ArgentinePesos", "aud" -> "AustralianDollars", 
 "awg" -> "ArubanFlorins", "azn" -> "AzerbaijaniManat", 
 "bam" -> "BosnianHerzegovinianMaraka", "bbd" -> "BarbadianDollars", 
 "bdt" -> "BangladeshiTaka", "bgn" -> "BulgarianLeva", 
 "bif" -> "BurundiFrancs", "bmd" -> "BermudaDollars", 
 "bnd" -> "BruneiDollars", "bob" -> "BolivianBolivianos", 
 "brl" -> "BrazilianReais", "bsd" -> "BahamianDollars", 
 "bwp" -> "BotswanaPula", "bzd" -> "BelizeDollars", 
 "cad" -> "CanadianDollars", "cdf" -> "CongoleseFranc", 
 "chf" -> "SwissFrancs", "clp" -> "ChileanPesos", 
 "cny" -> "ChineseYuan", "cop" -> "ColombianPesos", 
 "crc" -> "CostaRicanColones", "cve" -> "CapeVerdeanEscudos", 
 "czk" -> "CzechKoruny", "djf" -> "DjiboutiFrancs", 
 "dkk" -> "DanishKroner", "dop" -> "DominicanPesos", 
 "dzd" -> "AlgerianDinars", "egp" -> "EgyptianPounds", 
 "etb" -> "EthiopianBirr", "eur" -> "Euros", "fjd" -> "FijianDollars",
 "fkp" -> "FalklandIslandsPounds", "gbp" -> "BritishPounds", 
 "gel" -> "GeorgianLari", "gip" -> "GibraltarPounds", 
 "gmd" -> "GambianDalasi", "gnf" -> "GuineaFrancs", 
 "gtq" -> "GuatemalaQuetzales", "gyd" -> "GuyaneseDollars", 
 "hkd" -> "HongKongDollars", "hnl" -> "HonduranLempiras", 
 "hrk" -> "CroatianKuna", "htg" -> "HaitiGourdes", 
 "huf" -> "HungarianForints", "idr" -> "IndonesianRupiahs", 
 "ils" -> "IsraeliShekels", "inr" -> "IndianRupees", 
 "isk" -> "IcelandKronur", "jmd" -> "JamaicanDollars", "jpy" -> "Yen",
 "kes" -> "KenyanShillings", "kgs" -> "KyrgyzstanSom", 
 "khr" -> "CambodianRiels", "kmf" -> "ComorosFrancs", 
 "krw" -> "KoreanWon", "kyd" -> "CaymanIslandsDollars", 
 "kzt" -> "KazakhstanTenge", "lak" -> "LaoKips", 
 "lbp" -> "LebanesePounds", "lkr" -> "SriLankaRupees", 
 "lrd" -> "LiberianDollars", "lsl" -> "LesothoMaloti", 
 "mad" -> "MoroccanDirhams", "mdl" -> "MoldovanLei", 
 "mga" -> "MalagasyAriary", "mkd" -> "MacedonianDenars", 
 "mnt" -> "MongolianTugrik", "mop" -> "MacauPatacas", 
 "mro" -> "MauritanianOuguiya", "mur" -> "MauritiusRupees", 
 "mvr" -> "MaldivesRufiyaa", "mwk" -> "MalawiKwacha", 
 "mxn" -> "MexicanPesos", "myr" -> "MalaysianRinggits", 
 "mzn" -> "MozambiqueMeticais", "nad" -> "NamibianDollars", 
 "ngn" -> "NigerianNaira", "nio" -> "NicaraguaCordobas", 
 "nok" -> "NorwegianKroner", "npr" -> "NepaleseRupees", 
 "nzd" -> "NewZealandDollars", "pab" -> "PanamaBalboas", 
 "pen" -> "PeruvianSoles", "pgk" -> "PapuaNewGuineaKina", 
 "php" -> "PhilippinePesos", "pkr" -> "PakistaniRupees", 
 "pln" -> "PolishZlotych", "pyg" -> "ParaguayanGuaranies", 
 "qar" -> "QatarRials", "ron" -> "RomanianLei", 
 "rsd" -> "SerbianDinars", "rub" -> "RussianRubles", 
 "rwf" -> "RwandaFrancs", "sar" -> "SaudiArabianRiyals", 
 "sbd" -> "SolomonIslandsDollars", "scr" -> "SeychellesRupees", 
 "sek" -> "SwedishKronor", "sgd" -> "SingaporeDollars", 
 "shp" -> "SaintHelenaPounds", "sll" -> "SierraLeoneLeones", 
 "sos" -> "SomaliShillings", "srd" -> "SurinameDollars", 
 "std" -> "SaoTomeDobras", "svc" -> "ElSalvadorColones", 
 "szl" -> "SwazilandEmalangeni", "thb" -> "ThaiBaht", 
 "tjs" -> "TajikistanSomoni", "top" -> "TongaPaanga", 
 "try" -> "TurkishLiras", "ttd" -> "TrinidadTobagoDollars", 
 "twd" -> "TaiwanDollars", "tzs" -> "TanzanianShillings", 
 "uah" -> "UkraineHryven", "ugx" -> "UgandanShillings", 
 "usd" -> "USDollars", "uyu" -> "UruguayanPesos", 
 "uzs" -> "UzbekistanSom", "vnd" -> "VietnameseDong", 
 "vuv" -> "VanuatuVatu", "wst" -> "SamoanTala", 
 "xaf" -> "CentralAfricanCFAFrancs", "xcd" -> "EastCaribbeanDollars", 
 "xof" -> "WestAfricanCFAFrancs", "xpf" -> "PacificFrancs", 
 "yer" -> "YemenRiyals", "zar" -> "SouthAfricanRand", 
 "zmw" -> "ZambianKwacha"}

$StripeCurrencies = {"aed", "afn", "all", "amd", "ang", "aoa", "ars", "aud", "awg",
"azn", "bam", "bbd", "bdt", "bgn", "bif", "bmd", "bnd", "bob", "brl",
"bsd", "bwp", "bzd", "cad", "cdf", "chf", "clp", "cny", "cop", "crc",
"cve", "czk", "djf", "dkk", "dop", "dzd", "egp", "etb", "eur", "fjd",
"fkp", "gbp", "gel", "gmd", "gnf", "gtq", "gyd", "hkd", "hnl", "hrk",
"htg", "huf", "idr", "ils", "inr", "isk", "jmd", "jpy", "kes", "kgs",
"khr", "kmf", "krw", "kyd", "kzt", "lak", "lbp", "lkr", "lrd", "lsl",
"ltl", "lvl", "mad", "mdl", "mga", "mkd", "mnt", "mop", "mro", "mur",
"mvr", "mwk", "mxn", "myr", "mzn", "nad", "ngn", "nio", "nok", "npr",
"nzd", "pen", "pgk", "php", "pkr", "pln", "pyg", "qar", "ron", "rsd",
"rub", "rwf", "sar", "sbd", "scr", "sek", "sgd", "shp", "sll", "sos",
"srd", "std", "svc", "szl", "thb", "tjs", "top", "try", "ttd", "twd",
"tzs", "uah", "ugx", "usd", "uyu", "uzs", "vnd", "vuv", "wst", "xaf",
"xcd", "xof", "xpf", "yer", "zar", "zmw"}

$StripeNoCent = {"bif", "clp", "djf", "gnf", "jpy", "kmf", "krw",
"mga", "pyg", "rwf", "vnd", "vuv", "xaf", "xof", "xpf"}

$StripeInterpreterCountryList= {
 "AF" -> Entity["Country", "Afghanistan"], 
 "AL" -> Entity["Country", "Albania"], 
 "DZ" -> Entity["Country", "Algeria"], 
 "AS" -> Entity["Country", "AmericanSamoa"], 
 "AD" -> Entity["Country", "Andorra"], 
 "AO" -> Entity["Country", "Angola"], 
 "AI" -> Entity["Country", "Anguilla"], 
 "AG" -> Entity["Country", "AntiguaBarbuda"], 
 "AR" -> Entity["Country", "Argentina"], 
 "AM" -> Entity["Country", "Armenia"], 
 "AW" -> Entity["Country", "Aruba"], 
 "AU" -> Entity["Country", "Australia"], 
 "AT" -> Entity["Country", "Austria"], 
 "AZ" -> Entity["Country", "Azerbaijan"], 
 "BS" -> Entity["Country", "Bahamas"], 
 "BH" -> Entity["Country", "Bahrain"], 
 "BD" -> Entity["Country", "Bangladesh"], 
 "BB" -> Entity["Country", "Barbados"], 
 "BY" -> Entity["Country", "Belarus"], 
 "BE" -> Entity["Country", "Belgium"], 
 "BZ" -> Entity["Country", "Belize"], 
 "BJ" -> Entity["Country", "Benin"], 
 "BM" -> Entity["Country", "Bermuda"], 
 "BT" -> Entity["Country", "Bhutan"], 
 "BO" -> Entity["Country", "Bolivia"], 
 "BA" -> Entity["Country", "BosniaHerzegovina"], 
 "BW" -> Entity["Country", "Botswana"], 
 "BR" -> Entity["Country", "Brazil"], 
 "VG" -> Entity["Country", "BritishVirginIslands"], 
 "BN" -> Entity["Country", "Brunei"], 
 "BG" -> Entity["Country", "Bulgaria"], 
 "BF" -> Entity["Country", "BurkinaFaso"], 
 "BI" -> Entity["Country", "Burundi"], 
 "KH" -> Entity["Country", "Cambodia"], 
 "CM" -> Entity["Country", "Cameroon"], 
 "CA" -> Entity["Country", "Canada"], 
 "CV" -> Entity["Country", "CapeVerde"], 
 "KY" -> Entity["Country", "CaymanIslands"], 
 "CF" -> Entity["Country", "CentralAfricanRepublic"], 
 "TD" -> Entity["Country", "Chad"], 
 "CL" -> Entity["Country", "Chile"], 
 "CN" -> Entity["Country", "China"], 
 "CX" -> Entity["Country", "ChristmasIsland"], 
 "CC" -> Entity["Country", "CocosKeelingIslands"], 
 "CO" -> Entity["Country", "Colombia"], 
 "KM" -> Entity["Country", "Comoros"], 
 "CK" -> Entity["Country", "CookIslands"], 
 "CR" -> Entity["Country", "CostaRica"], 
 "HR" -> Entity["Country", "Croatia"], 
 "CU" -> Entity["Country", "Cuba"],
 "CY" -> Entity["Country", "Cyprus"], 
 "CZ" -> Entity["Country", "CzechRepublic"], 
 "CD" -> Entity["Country", "DemocraticRepublicCongo"], 
 "DK" -> Entity["Country", "Denmark"], 
 "DJ" -> Entity["Country", "Djibouti"], 
 "DM" -> Entity["Country", "Dominica"], 
 "DO" -> Entity["Country", "DominicanRepublic"], 
 "TL" -> Entity["Country", "EastTimor"], 
 "EC" -> Entity["Country", "Ecuador"], 
 "EG" -> Entity["Country", "Egypt"], 
 "SV" -> Entity["Country", "ElSalvador"], 
 "GQ" -> Entity["Country", "EquatorialGuinea"], 
 "ER" -> Entity["Country", "Eritrea"], 
 "EE" -> Entity["Country", "Estonia"], 
 "ET" -> Entity["Country", "Ethiopia"], 
 "FK" -> Entity["Country", "FalklandIslands"], 
 "FO" -> Entity["Country", "FaroeIslands"], 
 "FJ" -> Entity["Country", "Fiji"], 
 "FI" -> Entity["Country", "Finland"], 
 "FR" -> Entity["Country", "France"], 
 "GF" -> Entity["Country", "FrenchGuiana"], 
 "PF" -> Entity["Country", "FrenchPolynesia"], 
 "GA" -> Entity["Country", "Gabon"], 
 "GM" -> Entity["Country", "Gambia"], 
 "GZ" -> Entity["Country", "GazaStrip"], 
 "GE" -> Entity["Country", "Georgia"], 
 "DE" -> Entity["Country", "Germany"], 
 "GH" -> Entity["Country", "Ghana"], 
 "GI" -> Entity["Country", "Gibraltar"], 
 "GR" -> Entity["Country", "Greece"], 
 "GL" -> Entity["Country", "Greenland"], 
 "GD" -> Entity["Country", "Grenada"], 
 "GP" -> Entity["Country", "Guadeloupe"], 
 "GU" -> Entity["Country", "Guam"], 
 "GT" -> Entity["Country", "Guatemala"], 
 "GG" -> Entity["Country", "Guernsey"], 
 "GN" -> Entity["Country", "Guinea"], 
 "GW" -> Entity["Country", "GuineaBissau"], 
 "GY" -> Entity["Country", "Guyana"], 
 "HT" -> Entity["Country", "Haiti"], 
 "HN" -> Entity["Country", "Honduras"], 
 "HK" -> Entity["Country", "HongKong"], 
 "HU" -> Entity["Country", "Hungary"], 
 "IS" -> Entity["Country", "Iceland"], 
 "IN" -> Entity["Country", "India"], 
 "ID" -> Entity["Country", "Indonesia"], 
 "IR" -> Entity["Country", "Iran"],
 "IQ" -> Entity["Country", "Iraq"],
 "IE" -> Entity["Country", "Ireland"], 
 "IM" -> Entity["Country", "IsleOfMan"], 
 "IL" -> Entity["Country", "Israel"], 
 "IT" -> Entity["Country", "Italy"], 
 "CI" -> Entity["Country", "IvoryCoast"], 
 "JM" -> Entity["Country", "Jamaica"], 
 "JP" -> Entity["Country", "Japan"], 
 "JE" -> Entity["Country", "Jersey"], 
 "JO" -> Entity["Country", "Jordan"], 
 "KZ" -> Entity["Country", "Kazakhstan"], 
 "KE" -> Entity["Country", "Kenya"], 
 "KI" -> Entity["Country", "Kiribati"],
 "KW" -> Entity["Country", "Kuwait"], 
 "KG" -> Entity["Country", "Kyrgyzstan"], 
 "LA" -> Entity["Country", "Laos"], 
 "LV" -> Entity["Country", "Latvia"], 
 "LB" -> Entity["Country", "Lebanon"], 
 "LS" -> Entity["Country", "Lesotho"], 
 "LR" -> Entity["Country", "Liberia"], 
 "LY" -> Entity["Country", "Libya"], 
 "LI" -> Entity["Country", "Liechtenstein"], 
 "LT" -> Entity["Country", "Lithuania"], 
 "LU" -> Entity["Country", "Luxembourg"], 
 "MO" -> Entity["Country", "Macau"], 
 "MK" -> Entity["Country", "Macedonia"], 
 "MG" -> Entity["Country", "Madagascar"], 
 "MW" -> Entity["Country", "Malawi"], 
 "MY" -> Entity["Country", "Malaysia"], 
 "MV" -> Entity["Country", "Maldives"], 
 "ML" -> Entity["Country", "Mali"], 
 "MT" -> Entity["Country", "Malta"], 
 "MH" -> Entity["Country", "MarshallIslands"], 
 "MQ" -> Entity["Country", "Martinique"], 
 "MR" -> Entity["Country", "Mauritania"], 
 "MU" -> Entity["Country", "Mauritius"], 
 "YT" -> Entity["Country", "Mayotte"], 
 "MX" -> Entity["Country", "Mexico"], 
 "FM" -> Entity["Country", "Micronesia"], 
 "MD" -> Entity["Country", "Moldova"], 
 "MC" -> Entity["Country", "Monaco"], 
 "MN" -> Entity["Country", "Mongolia"], 
 "ME" -> Entity["Country", "Montenegro"], 
 "MS" -> Entity["Country", "Montserrat"], 
 "MA" -> Entity["Country", "Morocco"], 
 "MZ" -> Entity["Country", "Mozambique"], 
 "MM" -> Entity["Country", "Myanmar"], 
 "NA" -> Entity["Country", "Namibia"], 
 "NR" -> Entity["Country", "Nauru"], 
 "NP" -> Entity["Country", "Nepal"], 
 "NL" -> Entity["Country", "Netherlands"], 
 "NC" -> Entity["Country", "NewCaledonia"], 
 "NZ" -> Entity["Country", "NewZealand"], 
 "NI" -> Entity["Country", "Nicaragua"], 
 "NE" -> Entity["Country", "Niger"], 
 "NG" -> Entity["Country", "Nigeria"], 
 "NU" -> Entity["Country", "Niue"], 
 "NF" -> Entity["Country", "NorfolkIsland"], 
 "MP" -> Entity["Country", "NorthernMarianaIslands"], 
 "KP" -> Entity["Country", "NorthKorea"], 
 "NO" -> Entity["Country", "Norway"], 
 "OM" -> Entity["Country", "Oman"], 
 "PK" -> Entity["Country", "Pakistan"], 
 "PW" -> Entity["Country", "Palau"], 
 "PA" -> Entity["Country", "Panama"], 
 "PG" -> Entity["Country", "PapuaNewGuinea"], 
 "PY" -> Entity["Country", "Paraguay"], 
 "PE" -> Entity["Country", "Peru"], 
 "PH" -> Entity["Country", "Philippines"], 
 "PN" -> Entity["Country", "PitcairnIslands"], 
 "PL" -> Entity["Country", "Poland"], 
 "PT" -> Entity["Country", "Portugal"], 
 "PR" -> Entity["Country", "PuertoRico"], 
 "QA" -> Entity["Country", "Qatar"], 
 "CG" -> Entity["Country", "RepublicCongo"], 
 "RE" -> Entity["Country", "Reunion"], 
 "RO" -> Entity["Country", "Romania"], 
 "RU" -> Entity["Country", "Russia"], 
 "RW" -> Entity["Country", "Rwanda"], 
 "SH" -> Entity["Country", "SaintHelena"], 
 "KN" -> Entity["Country", "SaintKittsNevis"], 
 "LC" -> Entity["Country", "SaintLucia"], 
 "PM" -> Entity["Country", "SaintPierreMiquelon"], 
 "VC" -> Entity["Country", "SaintVincentGrenadines"], 
 "WS" -> Entity["Country", "Samoa"], 
 "SM" -> Entity["Country", "SanMarino"], 
 "ST" -> Entity["Country", "SaoTomePrincipe"], 
 "SA" -> Entity["Country", "SaudiArabia"], 
 "SN" -> Entity["Country", "Senegal"], 
 "RS" -> Entity["Country", "Serbia"], 
 "SC" -> Entity["Country", "Seychelles"], 
 "SL" -> Entity["Country", "SierraLeone"], 
 "SG" -> Entity["Country", "Singapore"], 
 "SK" -> Entity["Country", "Slovakia"], 
 "SI" -> Entity["Country", "Slovenia"], 
 "SB" -> Entity["Country", "SolomonIslands"], 
 "SO" -> Entity["Country", "Somalia"], 
 "ZA" -> Entity["Country", "SouthAfrica"], 
 "KR" -> Entity["Country", "SouthKorea"], 
 "SD" -> Entity["Country", "SouthSudan"], 
 "ES" -> Entity["Country", "Spain"], 
 "LK" -> Entity["Country", "SriLanka"], 
 "SD" -> Entity["Country", "Sudan"], 
 "SR" -> Entity["Country", "Suriname"], 
 "SJ" -> Entity["Country", "Svalbard"], 
 "SZ" -> Entity["Country", "Swaziland"], 
 "SE" -> Entity["Country", "Sweden"], 
 "CH" -> Entity["Country", "Switzerland"], 
 "SY" -> Entity["Country", "Syria"], 
 "TW" -> Entity["Country", "Taiwan"], 
 "TJ" -> Entity["Country", "Tajikistan"], 
 "TZ" -> Entity["Country", "Tanzania"], 
 "TH" -> Entity["Country", "Thailand"], 
 "TG" -> Entity["Country", "Togo"], 
 "TK" -> Entity["Country", "Tokelau"], 
 "TO" -> Entity["Country", "Tonga"], 
 "TT" -> Entity["Country", "TrinidadTobago"], 
 "TN" -> Entity["Country", "Tunisia"], 
 "TR" -> Entity["Country", "Turkey"], 
 "TM" -> Entity["Country", "Turkmenistan"], 
 "TC" -> Entity["Country", "TurksCaicosIslands"], 
 "TV" -> Entity["Country", "Tuvalu"], 
 "UG" -> Entity["Country", "Uganda"], 
 "UA" -> Entity["Country", "Ukraine"], 
 "AE" -> Entity["Country", "UnitedArabEmirates"], 
 "GB" -> Entity["Country", "UnitedKingdom"], 
 "US" -> Entity["Country", "UnitedStates"], 
 "VI" -> Entity["Country", "UnitedStatesVirginIslands"], 
 "UY" -> Entity["Country", "Uruguay"], 
 "UZ" -> Entity["Country", "Uzbekistan"], 
 "VU" -> Entity["Country", "Vanuatu"], 
 "VA" -> Entity["Country", "VaticanCity"], 
 "VE" -> Entity["Country", "Venezuela"], 
 "VN" -> Entity["Country", "Vietnam"], 
 "WF" -> Entity["Country", "WallisFutuna"], 
 "WE" -> Entity["Country", "WestBank"], 
 "EH" -> Entity["Country", "WesternSahara"], 
 "YE" -> Entity["Country", "Yemen"], 
 "ZM" -> Entity["Country", "Zambia"], 
 "ZW" -> Entity["Country", "Zimbabwe"]}

End[];
 
EndPackage[];